### ISSUE TITLE
Bulk organization export improvements

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#100]
A group of U-M students is doing some mapping work. It would be super helpful for them to have an improved organization export that includes:
- EIN
- NTEE
- Address
- Dollars with no characters / whitespace (Excel handles it fine but doubtful others will)

**Comment by bnchdrff** [comment]
Note for discussion: the NTEE currently pretty-prints names and doesn't use the actual machine name / code.

**Comment by hampelm** [comment]
It looks like dollars are still exporting as strings. Also, it looks like we default addresses to "Detroit, MI United States" when that might not be appropriate. Should that be in this ticket or a separate one?

**Comment by bnchdrff** [comment]
fixed the amount formatting thing!

regarding the addresses... that's a data quality thing that isn't solvable by code unfortunately.
