### ISSUE TITLE
Resource URLs point at http site

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#103]
The resources at `data.detroitledger.org` currently point to the HTTP site. They're redirected, but Chrome won't load them. Though the site is super fast and simple now, some of the super helpful functionality is missing (eg find-ahead search for node references)

![screen shot 2015-01-11 at 8 53 00 am](https://cloud.githubusercontent.com/assets/86435/5695402/81debdf2-996f-11e4-91ce-b8a8fc972a43.png)

**Comment by bnchdrff** [comment]
The new reverse proxy caused this bug: I fixed it by setting a base_url
manually in Drupal's settings.

On 01/11, Matt Hampel wrote:

> The resources at `data.detroitledger.org` currently point to the HTTP site. They're redirected, but Chrome won't load them. Though the site is super fast and simple now, some of the super helpful functionality is missing (eg find-ahead search for node references)
> 
> ![screen shot 2015-01-11 at 8 53 00 am](https://cloud.githubusercontent.com/assets/86435/5695402/81debdf2-996f-11e4-91ce-b8a8fc972a43.png)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/detroitledger/gnl_profile/issues/103

## 

Benjamin Chodoroff
tel:3139992892
https://detriot.org
