### ISSUE TITLE
Add a couple more content views/filtering options?

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#104]
As we improve content, it'd be great to have a way to find specific deficient content: 
- Grants without tags
- Grants without sources
- ... descriptions
- Orgs without descriptions
- Orgs without tags

Is it straightforward to add more options to the filters? 
![screen shot 2015-01-23 at 10 44 45 am](https://cloud.githubusercontent.com/assets/86435/5877352/eea9090c-a2ec-11e4-931d-530cf69d1750.png)

Or a better way to drill down?

**Comment by bnchdrff** [comment]
I set up https://data.detroitledger.org/admin/orgs in 97345ee14ff817a060c96906912e361c77228573 -- it's linked as "Manage organizations" in the footer menu --  we can add all sorts of filters there!

**Comment by hampelm** [comment]
Historical note: I also set up https://www.detroitledger.org/#!/quality to track & link to deficient orgs
