### ISSUE TITLE
Huge set of federal grant awards 

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#106]
I pulled a [huge list of federal subgrantees](http://www.usaspending.gov/subaward-search?form_fields=%7B%22recip_city%22%3A%22Detroit%22%2C%22recip_state%22%3A%22MI%22%2C%22fyear%22%3A%5B%222015%22%2C%222014%22%2C%222013%22%5D%2C%22sub_spending_cat%22%3A%5B%22sg%22%5D%7D&sort_by=dollars&per_page=25) in Detroit from USASpending. 

I don't know that this sub-award data is complete, but it doesn't seem to include the data in #107. 

Mapping of our fields to their fields: 
- Federal Award ID =  `prime_award_federal_award_id`
- Recipient = `subawardee_name`
- Funder :`subaward_major_agency_name`
- `subawardee_dba_name` often refers to the department or program (eg if Recipient is "CITY OF DETROIT', `subawardee_dba_name` might be "MAYOR'S OFFICE"
  *\* `subawardee_street`, `subawardee_zipcode`, etc might be useful for filling in addresses
- Amount: `subaward_amount` 
- From: `subaward_date` 
- To: might be `subaward_report_month` + `subaward_report_year` possibly? I don't know if this is even included in the data. From the [reporting guidelines](https://www.fsrs.gov/#a-faqs): 

> The prime recipient will have until the end of the month plus one additional month after an award or sub-award is obligated to fulfill the reporting requirement. For example, if a sub-award was made on October 15, 2010, the prime recipient has until November 30, 2010 to report the sub-award information.

Descriptions:
- `prime_award_project_description` and `prime_award_program_title` (often the same?) 
- `subaward_project_description`
- `subaward_CFDA_program_number_title_codes` (eg "14.238 Shelter Plus Care")

**Comment by hampelm** [comment]
I forgot to link up the spreadsheet https://docs.google.com/a/localdata.com/spreadsheets/d/16dXuV63qyVkT4irhkPUchi0qnF2MOc3EWRDupFnLVqY/edit?usp=drive_web

**Comment by hampelm** [comment]
All right, I've got a cleaned copy here @bnchdrff https://docs.google.com/a/localdata.com/spreadsheets/d/1BxVS0mtIwL5HehGmgfrR-aBTPvEhp_cq0gM4IMDwUeo

I can also share the Refine steps (though some were done in Excel)

**Comment by bnchdrff** [comment]
finished the USA_Grants migration last night... ran into a speedbump when i realized that the federal award id isn't unique.. came up with a detroit ledger-specific unique id scheme (import batch # + row # - 1) that should work across any future imports.

running import on live now!!!

# before

![screenshot from 2015-03-31 08 18 00](https://cloud.githubusercontent.com/assets/99194/6918733/f1b1bbfa-d77e-11e4-9914-2856af05de14.png)

# AFTER

![screenshot from 2015-03-31 08 20 57](https://cloud.githubusercontent.com/assets/99194/6918737/f75cc446-d77e-11e4-8a2f-7d603907424e.png)
