### ISSUE TITLE
Board member dates and grant dates use different formats

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#112]
Grant dates (eg `field_start_date`) are served in the format  `ddd, DD MMM YYYY HH:mm:ss ZZ`. Board member dates are in the somewhat easier to parse format `YYYY-MM-DD HH:MM:SS`. We should use one format consistently.

**Comment by bnchdrff** [comment]
Indeed. I'll switch em!

**Comment by bnchdrff** [comment]
Hmm. shouldn't we include timezone?

**Comment by bnchdrff** [comment]
`ddd, DD MMM YYYY HH:mm:ss ZZ` is easy to parse with Date.parse...

**Comment by hampelm** [comment]
That works for me!
