### ISSUE TITLE
Getting orgs sorted by amount funded/recieved? 

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#116]
Can the API return a list of orgs sorted by amount funded/received?

I tried a query in the format
https://data.detroitledger.org/api/1.0/orgs.jsonp/&limit=5&sort[n.org_grants_funded]=DESC and got a SQL error:

```
["SQL error at /api/1.0/orgs.jsonp/&amp;limit=5&amp;sort[n.org_amount_funded]=DESC"]
```

 I realized that the field is probably computed so it might be tricky.

**Comment by bnchdrff** [comment]
Use special sort keys `funded` and `received` -- just added this to the apiary docs! sorry it wasn't there b4.

**Comment by hampelm** [comment]
Sweet thanks!
