### ISSUE TITLE
Don't make unpublished nodes available through the API

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#119]
I just unpublished a node (https://data.detroitledger.org/node/1902/edit, though it may be deleted by the time you read this). It was still available on the Robert Wood Johnson page and by direct link to the node ID. I didn't check the aggregate numbers but I assume it was in there too.

**Comment by bnchdrff** [comment]
The retrieve operation wasn't testing for published/unpublished, but the index & stats calculations were.
