### ISSUE TITLE
Make sure data imports are associated with a user

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#12]

**Comment by hampelm** [comment]
bump @bnchdrff -- can we make sure node imports are associated with a user other than Admin? Do we need to create a fixture for a generic user?

**Comment by bnchdrff** [comment]
Do we want to credit certain users for adding/editing content in the UI anywhere? If not then we can just leave it as admin... but if we do, maybe we can create a user "imported data" or something

**Comment by hampelm** [comment]
I think it's fine to associate the data with the Admin user. If it's easy to post-hoc rename the admin to Jessica, even better (and more user friendly :+1:)
