### ISSUE TITLE
Add news feature

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#121]
Allow us to store short news snippets and links associated with organizations. 

Fields: 
- Title (text field)
- Description (probably a 3-5 line text box for a short summary)
- Link (text field)
- Date (defaults to current date)
- Organization relation (ideally would allow selecting multiple orgs, for stories that mention several)
- Optional: grant relation (link to multiple related grants)

Ideally, the API endpoint for organizations would be updated to include a `news` property with data that looks something like this:

```
...
news: [{
  title: "Title",
  description: "Description...",
  link: "http://example.com/news/123",
  date: [timestamp in a standard format],
  id: ID_OF_NEWS_PIECE (nid?)
  organizations: [{  <--- Org references can come later if it's annoying
    name: "Focus:HOPE",
    id: LEDGER_ID
  },...]
}...]
...
```

If you add the grant relation, the grant API might also need updating to include related news items.

**Comment by hampelm** [comment]
Or the news endpoint can be separate from the main org endpoint. Eg it could be `/orgs/123/news`

**Comment by bnchdrff** [comment]
news added!!1 :newspaper: available on orgs, but not grants quite yet. will work on that.

**Comment by bnchdrff** [comment]
added news prop to grant resource.

**Comment by bnchdrff** [comment]
adding related grants to news items isn't super easy because the titles are just "org -> org" - we could offer a more descriptive title maybe, with the grant id & date?

**Comment by hampelm** [comment]
Without knowing how easy or hard it is, one idea for titles is "$150,000 from A to B, 2012-2013"

That's really long, though.

I'd be fine skipping related grants on news items for now.

**Comment by jessicamcinchak** [comment]
Agreed that gets lengthy fast. 

Seems less important to tag related grants to news because those grants likely have said news article as their source anyways? Maybe it'd make more sense (and hopefully be easier) to work in the opposite direction -- to be able to source a grant we add to an existing news article (with a link to the Ledger news entry, rather than external page), and that'd happen on a grant-by-grant basis.

**Comment by hampelm** [comment]
@bnchdrff  It's live on data.detroitledger.org!! Is it good for Sarah to go, or should we hold off?

**Comment by bnchdrff** [comment]
It's good to go!
