### ISSUE TITLE
POST to flags enpoint gives 500

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#123]
via @jessicamcinchak 

To reproduce:
- Go to any grant or org place
- Click "Report missing or inaccurate data" and submit a report 
- The request will result in this error:

```
Status Code:500 Internal Server Error: An error occurred (22003): SQLSTATE[22003]: Numeric value 
out of range: 1264 Out of range value for column 'field_ip_value' at row 1
```

**Comment by bnchdrff** [comment]
Super weird, not sure why this doesn't work all of a sudden but the ip addy field is useless anyways so i'm disabling it for now :hammer:
