### ISSUE TITLE
NTEE codes don't show correct total given

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#128]
They show received, not given :-/

**Comment by bnchdrff** [comment]
funded & received are separate values:

```
totals: Object
funded: 641415920
received: 2980966
```

**Comment by bnchdrff** [comment]
as seen in https://data.detroitledger.org/api/1.0/ntees/510.json

**Comment by hampelm** [comment]
Yeah, this is my error (didn't make that clear)

**Comment by bnchdrff** [comment]
Issue moved to [detroitledger/detroitledger #93](https://github.com/detroitledger/detroitledger/issues/93) via [**ZenHub.io**](https://www.zenhub.io/)
