### ISSUE TITLE
Remove the grant title field

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#13]

**Comment by hampelm** [comment]
Apparently this is hard. We can use [automatic nodetitles](https://drupal.org/project/auto_nodetitle), but that isn't picked up by Features.

**Comment by bnchdrff** [comment]
On Thu 04 Jul 2013 08:36:18 PM IST, Matt Hampel wrote:

> Apparently this is hard. We can use automatic nodetitles, but that
> isn't picked up by Features.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/detroitledger/gnl_profile/issues/13#issuecomment-20481766.

I vote for using drupal.org/project/title

I can set this up when I get back from bad-internet-land.. until then 
we can hide the title in presentation layer
