### ISSUE TITLE
Figure out why we don't have Harriet Tubman data

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#140]
EIN 10885325
Guidestar has 'em
http://www.guidestar.org/profile/01-0885325

**Comment by hampelm** [comment]
Ah, we don't have the leading zero.

**Comment by bnchdrff** [comment]
why don't we just cast to int before the api request?

**Comment by hampelm** [comment]
That would work. I'd like us to be as true to the source data as possible (will help if we have other consumers in the future, too)

**Comment by bnchdrff** [comment]
i'm fairly positive that an EIN is always a number and never requires symbols. according to wikipedia the dash after the first two digits is a cosmetic choice. we can display the ein with a dash but i think it makes sense to store & query as a number.

**Comment by hampelm** [comment]
Ah! Could we cast the EIN to an int server-side? And maybe also remove dashes. That way it wouldn't matter if the requester had the leading zero.

**Comment by bnchdrff** [comment]
we could def do that!
