### ISSUE TITLE
Site name should be set by default

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#19]
The site should be called "The Detroit Ledger" after an install.

**Comment by bnchdrff** [comment]
For dev I kinda prefer for the site to be named something unique... so I set it up to default to the server name: https://github.com/detroitledger/gnl_profile/blob/7.x-1.x/gnl_profile.profile#L4

We could do some sort of if ($dev_env) site name is server name else site name is "The Detroit Ledger" type thing...
