### ISSUE TITLE
Let's cache all the things!

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#2]
(in production)

It already takes a second or so to generate the homepage on my SSD-backed laptop.

**Comment by bnchdrff** [comment]
server will do this for us :)

**Comment by hampelm** [comment]
Just want to confirm -- are there any settings we need to change, or configuration we need to encode?

**Comment by bnchdrff** [comment]
On barracuda/octopus servers, any domain with _.dev._ is not cached. All other domains get all sorts of caching: http://omega8.cc/speed-booster-redis-boost-and-advagg-108 - n.b. much of this caching is for anon users only... but that's ok for us right now.
