### ISSUE TITLE
Organizations should have a much higher search weight than grants

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#21]
Is this even possible with vanilla search?

**Comment by bnchdrff** [comment]
Not so possible... if we want fancy searching I'd say we should use Solr. It's nice.

**Comment by hampelm** [comment]
Can we search just the grants content type? I'll look into that.

**Comment by bnchdrff** [comment]
Added org-specific search to our orgs view in detroitledger/gnl_schema@7b9c087bd0afcde51f57447e9d7a332597a20dbe

Until we set up solr (which I would like to do eventually when we need any sort of full text and facet search), I think we should have separate search fields for org/grant/org type/etc... if we wanted to get fancy we could combine all the fields into a visualsearch.js widget.
