### ISSUE TITLE
Styles should be compiled by default

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#22]
We shouldn't have to do that by hand.

**Comment by bnchdrff** [comment]
do you mean on deploy or during development?

for doing dev locally you can either run guard from within the theme dir, or manually compile `compass compile` after changes

i'll set up a guard process on the aug2013.dev site so changes will trigger a recompile

**Comment by hampelm** [comment]
I meant on deployment, so looks like that's handled. 

There's guard instructions in the theme readme now, so we should be good here.
