### ISSUE TITLE
create services view for org names and grant totals

### ISSUE THREAD

**Issue by bnchdrff** [detroitledger/gnl_profile#24]
i tried doing it quickly but the results didn't include aggregate fields for some reason :frowning:

**Comment by bnchdrff** [comment]
this might be related to our problem: https://drupal.org/node/1938478

**Comment by bnchdrff** [comment]
also this: https://drupal.org/node/1905690

**Comment by hampelm** [comment]
For v1, can we just say that the API requires consumers to sum themselves?

## 

Sent from mobile
(734) 846-5010

**Comment by bnchdrff** [comment]
i'm good w/ that

**Comment by bnchdrff** [comment]
fixed in detroitledger/gnl_schema@52fe8f126b85bec6bc7ff24061cce0e9c9b4aa86
