### ISSUE TITLE
Numbers in JSON should not be quoted

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#26]
Numbers are a [native primitive type in JSON](http://www.ietf.org/rfc/rfc4627.txt) and should not be quoted.

**Comment by bnchdrff** [comment]
detroitledger/gnl_fields@1a5323f fixes node/entity row styled views, but not field ones. fix for the latter is upcoming!

**Comment by bnchdrff** [comment]
yaaaaaaay
