### ISSUE TITLE
What data is coming back with all_grants?

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#33]
Sample query: `http://aug2013.dev.detroitledger.org/api/1.0/views/all_grants.json/?display_id=grants_services&limit=2000`

More than 2,000 objects are returned, but we shouldn't have that many grants. Some of them have aggregate amounts -- are organizations being included as well?

**Comment by bnchdrff** [comment]
Funky. This might be an artifact of development crap in this working site. Time to re-deploy i think. maybe tomorrow morn?

**Comment by bnchdrff** [comment]
oh i found the problem - all_grants selects all grants and organizations. fixed!
