### ISSUE TITLE
all_grants endpoint data is hard to access

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#35]
To get the grant amount, you have to run `parseInt(data[i].field_funded_amount.und[0].value)`

It would be friendlier to instead do `data[i].amount`.

Same for source, body, date, etc.

**Comment by bnchdrff** [comment]
all_grants is currently spitting out the node object, will all its display/internationalization friendly biz going on. I'll create another view display with a simplified output similar to what we have set up for org_totals_services...

**Comment by bnchdrff** [comment]
fixed in views on dev site - not exported to code - if it looks good i'll patch this in!

aug2013.dev.detroitledger.org/api/1.0/views/all_grants.jsonp/?display_id=grants_services&limit=3000&callback=hi

**Comment by bnchdrff** [comment]
applied in detroitledger/gnl_schema@dd8b7a7cf6e6a370628f64b1403dd5092540de21
