### ISSUE TITLE
improve API

### ISSUE THREAD

**Issue by bnchdrff** [detroitledger/gnl_profile#37]
boost doesn't work: https://drupal.org/node/1219484

**Comment by bnchdrff** [comment]
see http://docs.detroitledger.apiary.io/ for docs

recent additions:
- new resources (orgs and grants) spit out cleaned-up data
- filter by title for orgs and grants indexes
- filter by total grants received and funded for orgs index
- offsets/limits for orgs and grants indexes

todo:
- include names for referenced taxonomy terms and maybe other things?
- performance audit (although it's running much faster now!)
- ssl
- ??? probably other stuff!

**Comment by hampelm** [comment]
Are the recent additions listed code additions or also todos?

## 

Sent from mobile
(734) 846-5010

**Comment by bnchdrff** [comment]
In code! https://github.com/bnchdrff/gnl_api/blob/7.x-1.x/gnl_api.module

It's installed on data.detroitledger.org

**Comment by bnchdrff** [comment]
I updated docs at http://docs.detroitledger.apiary.io/ to reflect some changes (no more POSTing searches to make things simpler, for example)

**Comment by bnchdrff** [comment]
it'd probably be nice to put the API docs under version control in the gnl_api module.

today i'll move gnl_api to the detroitledger org github account + add the doc

**Comment by hampelm** [comment]
@bnchdrff Should API issues go under this repo, or should we wait for the `gnl_api` repo?

**Comment by hampelm** [comment]
Two issues, so I don't forget them:

1: The orgs endpoint currently returns an array of organizations keyed by id: 

`{"7632": {...}, ... }`

The convention would be to have them in an ordered list under the `organizations` property, like so:

```
{
  organizations: [
    { ... }, ...
  ]
}
```

2: Whoops already forgot #2.

**Comment by hampelm** [comment]
Oh yeah. Idea number two is should we use `organizations` instead of `orgs` to be pedantic & predictable?

**Comment by bnchdrff** [comment]
Idea 1 makes sense to me.

As far as idea 2 goes.... changing from org to organization seems ok, although I would prefer shorter. In either case we should be consistent.

I'll start a branch to cover the first thing and will do the second after that.

**Comment by bnchdrff** [comment]
Also... I can't remember... do we want `id`s to live in `id` or `_id` or is a type-indicating property name best (like grant_id or org_id)?

**Comment by bnchdrff** [comment]
this PR fixes the first thing

to rename orgs to organizations we'd need to do some heavier lifting if we want to keep the internally-used / database table / machine name consistent with the public-facing name.
