### ISSUE TITLE
API: send grant amounts as values

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#44]
Currently, we send the grant amount as an object:

```
field_funded_amount: {
  value: '100000'
}
```

It would be more straightforward to make it just a string or integer: 

```
field_funded_amount: '100000'
```

**Comment by bnchdrff** [comment]
oops, forgot to note in my commit message: https://github.com/bnchdrff/gnl_api/commit/728694258db0aa1a82720408a45273a3662bfd38 fixes this
