### ISSUE TITLE
Grant endpoint: field_source could just be a string? 

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#46]
Right now, for a grant, `field_source` is an object with these properties: 

```
format: null
safe_value: "Guidestar; IRS 990 2011"
value: "Guidestar; IRS 990 2011"
```

Just using the value would be simpler.

**Comment by bnchdrff** [comment]
Yes that'd make sense... one value is sanitized and the other isn't but we don't really need that for this field.

**Comment by bnchdrff** [comment]
so, now we're only including the unsanitized value for field_source and field_internal_notes - this means cleaning happens in the frontend

**Comment by hampelm** [comment]
What sort of cleaning can be expected?

**Comment by bnchdrff** [comment]
It's escaped to fit the output format (e.g. as json it'd have json terminators escaped)

The safe_value would be escaped for html output, generally... Most js template engines handle this anyways (`{{var}}` vs `{{{unescaped}}}` in mustache) so it makes sense to only do it once.
