### ISSUE TITLE
Undefined index: field_recipient

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#57]
If you browse to an organization while logged in (eg http://data.detroitledger.org/content/us-department-housing-and-urban-development-hud-adult-well-being-services), you get a big notice like this:

```
Notice: Undefined index: field_recipient in include() (line 3 of /srv/www/drupal/profiles/gnl_profile/themes/gnl_theme/templates/node/node--grant--grantee_only.tpl.php).
```

**Comment by bnchdrff** [comment]
This was caused by some imported grants lacking a funder or recipient due to typos
