### ISSUE TITLE
Prefill values in the grant creation form

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#61]
We'll be creating a lot of grants. To make it faster, we can prefill some fields on the grant form. My ideas:
1. Carry the source forward 
2. Carry the funder forward 
3. Maybe carry the start/end date forward, because they are a lot of keystrokes

I think the first two make sense because we'll often do a bunch of grants from the same source.

**Comment by bnchdrff** [comment]
mr. github, "almost fixes" is OBVIOUSLY not the same as "fixes" :angry: :cake: :fish_cake:
