### ISSUE TITLE
Static page API

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#63]
It'd be helpful to have a simple API for static pages. Something like `/api/pages/page-slug-here` would make it easy to have clean URLs in the backbone site. Alternately, we could add jekyll to the backbone frontend.

**Comment by bnchdrff** [comment]
workin on it - also adding our donation processing endpoint

**Comment by bnchdrff** [comment]
oops. not really fixed yet. i will add a "path" property, and also allow searching by the path slug.

**Comment by bnchdrff** [comment]
added path filter! use like so: `https://data.detroitledger.org/api/1.0/pages.json?filters[path]=/content/transparency`

**Comment by bnchdrff** [comment]
of note: path is set on CMS side, and can be changed on creation or edit of a page
