### ISSUE TITLE
Sort everything by anything

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#65]
Younger grants should be listed first

**Comment by bnchdrff** [comment]
working on this & will finish tomorrow

deep thoughts, for when i come back to this:

how can i dynamically build the lightest-weight query possible given the needed `join`s, `sort`s, and `order by`s? currently it's a nasty mess of code blocks. might be time to refactor.

so far i've built filters and sorts on a field-by-field basis... if possible this should be abstracted.

**Comment by camarqui** [comment]
If possible it would be easier to use and see the information if each group of years were clearly distinct from one another

**Comment by bnchdrff** [comment]
can we do sorting in the frontend, since things are going to get re-sorted anyways and `order by` is expensive?

**Comment by bnchdrff** [comment]
actually frontend sort only kinda makes sense. a better question: which queries should offer sorting?

**Comment by camarqui** [comment]
Would it be possible for all queries to offer sorting?

**Comment by bnchdrff** [comment]
ok - a sort can now be added as an argument!

sort[fieldname]=ASC|DESC

caveat: fieldname is passed into our query builder as a MySQL table.column, so it changes from query to query.

another caveat: sometimes a certain sort will require additional joins. this is why i added https://github.com/detroitledger/gnl_profile/commit/f3bc2abe9c22dc054cd9bd1a0633c0353c92147d#diff-0c1c4a4a6ef8a8922b7a265879c0ae04R338

adding a funded_amount sort to the grants index query looks like this: `https://data.detroitledger.org/api/1.0/grants?limit=1&sort[fdffa.field_funded_amount_value]=DESC`

if this gets too annoying we can figure out a better solution for mapping api field identifiers back to their mysql roots & auto-building JOIN/ORDER BY stuff on the fly.
