### ISSUE TITLE
update tampermonkey script

### ISSUE THREAD

**Issue by jessicamcinchak** [detroitledger/gnl_profile#68]
alt+o no longer works to grab addresses from state db

**Comment by hampelm** [comment]
why is there a monkey tampering with our stuff. that's my job.

**Comment by bnchdrff** [comment]
i've tested in chrome and firefox. worked in both... but... in chrome i had to reinstall the script. i think a tampermonkey update may have uninstalled it or something. or maybe i just never installed it on this computer.

for testing:

first, install Greasemonkey (for firefox) or Tampermonkey (for chrome)

then, go to https://gist.github.com/bnchdrff/6652038 and click on "View Raw"

if greasemonkey (in firefox) or tampermonkey (chrome) is installed, you should get a prompt to "Install" - install it! or reinstall it (why not right?)

then, go to an org edit page, like this one, and, ensuring you aren't focused on a text field (maybe click on the "edit organization" text to ensure this) press alt and o on the keyboard

a new tab should open up with the LARA website, and many fields in the org edit page should be auto-populated with address and tags and stuff.

**Comment by jessicamcinchak** [comment]
Hey!

Turns out I was due for a reinstall.

It works!  I updated Cass Community Social Services.  It automatically
populated fields, but a new tab for the LARA site didn't open..

**Comment by jessicamcinchak** [comment]
Wait.. I get the new window on most orgs I'm updating now, that one was a
funny exception??

On Wed, May 7, 2014 at 1:50 PM, Jessica McInchak <jessica.mcinchak@gmail.com

> wrote:
> 
> Hey!
> 
> Turns out I was due for a reinstall.
> 
> It works!  I updated Cass Community Social Services.  It automatically
> populated fields, but a new tab for the LARA site didn't open..
> 
> On Wed, May 7, 2014 at 12:15 PM, Benjamin Chodoroff <

**Comment by bnchdrff** [comment]
NICE!

Yeah sometime it's laggy but that is unfortunately due to LARA being slow, in my experience.

**Comment by bnchdrff** [comment]
If it's disruptive for the new tab to open, we can disable that and just do the autofill and maybe pop up a button to open the record in a new window if it looks funky...

**Comment by bnchdrff** [comment]
resolving this for now - pls reopen if there are issues!
