### ISSUE TITLE
Carry over year 

### ISSUE THREAD

**Issue by camarqui** [detroitledger/gnl_profile#72]
On the new grant form, have the date information carry over from a previous entry to the next entry. This will make it faster to enter multiple grants from the same source / batch.

**Comment by camarqui** [comment]
The date of the previous grant are still not auto filling when a new grant is created in administration.

**Comment by bnchdrff** [comment]
I still haven't worked on this - will be doing so tomorrow though!

**Comment by camarqui** [comment]
Oh sorry! there was a tag on here that said ready and I thought that meant the changes were ready.
