### ISSUE TITLE
Search Error Forgiveness 

### ISSUE THREAD

**Issue by camarqui** [detroitledger/gnl_profile#73]
- Is the search field forgiving of spelling errors? 
- Will it try find grants and organizations based on just key words instead of an organization's complete names? (for instance could I search "urban renewal" or "transportation" and receive a search result?) 
- I also think the search field could be more specialized - perhaps include an advanced search function or have a radio button that differentiates what information is returned in a search (organizations only, grants only, grants with this name, ect)

**Comment by hampelm** [comment]
Merging this with #42
