### ISSUE TITLE
Improve pages API

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#84]
This is fairly minor. 

The current pages API works like so: 

Endpoint: `https://data.detroitledger.org/api/1.0/pages.jsonp/?filters[path]=/content/about-detroit-ledger`

 Result: an array with 1 page.

Ideal functionality:

Endpoint: `https://data.detroitledger.org/api/1.0/pages/about-detroit-ledger.json`

Result: An object with 1 page

**Comment by bnchdrff** [comment]
"about-detroit-ledger" is a slug that might change by an editor in the CMS -- i'd prefer to have pages identified by a unique ID that won't change....

**Comment by hampelm** [comment]
If the lookup is by NID, what's the best way to do clean URLs on the client? Eg, I don't want to present users with something like `/pages/312` (and it's better for SEO if we have human-readable URLs).

**Comment by bnchdrff** [comment]
It depends on how the menu system works. How are we building the menu currently? i.e. how does the frontend know which pages are available and in what order are the links displayed?

**Comment by hampelm** [comment]
Here's how it works right now: the URLs are hardcoded in the navigation (eg `http://detroitledger.github.io/ledger-backbone/#/about-detroit-ledger`). Then, the backbone router resolves that slug to a view with a model: https://github.com/detroitledger/ledger-backbone/blob/gh-pages/js/models/pages.js#L21

**Comment by bnchdrff** [comment]
how about a page-by-slug/:slug endpoint that returns a single page if an exact match for the slug exists, otherwise 404?

**Comment by hampelm** [comment]
sure!

On Mon, Jun 9, 2014 at 3:34 PM, Benjamin Chodoroff <notifications@github.com

**Comment by bnchdrff** [comment]
actually how bout accepting either an ID or slug... on /pages,
like `pages/2` or `pages/about-detroit-ledger` would return the same object

**Comment by bnchdrff** [comment]
slashes don't work as an argument for pages/:page

to be consistent w/ frontend routing and also to deal with this issue, i removed 'content/' from our 3 page paths

**Comment by bnchdrff** [comment]
& also the interview and outreach pages.
