### ISSUE TITLE
Show orgs with most granted, most received 

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#86]
The current homepages shows orgs ordered by amount funded. Can we replicate that sort order in the orgs API? eg, `?sort=amount_funded&dir=desc`

**Comment by bnchdrff** [comment]
example queries: `https://data.detroitledger.org/api/1.0/orgs?sort[received]=DESC` `https://data.detroitledger.org/api/1.0/orgs?sort[funded]=DESC`
