### ISSUE TITLE
How hard would it be to have a "recent changes" feed

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#90]
A list of recent additions, edits, etc.

**Comment by bnchdrff** [comment]
Ez. Timestamps for created+modified (if they're the same then it's a new item), path to item + human-readable summary of change + title of item changed?

```
{
  created: 1403027869,
  changed: 1403027869,
  summary: "New grant: Detroit Ledger granted Detroit Economic Growth Association $138,000,000,000.",
  title: "Detroit Ledger -> Detroit Economic Growth Association"
}
```

**Comment by hampelm** [comment]
Can I just construct a query of grants and sort on created?

M

**Comment by bnchdrff** [comment]
Yes, but you'd only get grant edits that way, and not organization edits.

**Comment by hampelm** [comment]
That's probably fine. I could mix in the orgs.

M
