### ISSUE TITLE
Bulk / CSV export

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#91]
Can we get a CSV export of all grants?

**Comment by bnchdrff** [comment]
For sure... what fields?

**Comment by hampelm** [comment]
to, from, federal IDs for both, ntees, amount, source, date added, notes?

**Comment by bnchdrff** [comment]
sounds good. + IDs for the grant and to/from orgs

**Comment by hampelm** [comment]
Bulk export done!
