### ISSUE TITLE
eliminate autofill for "edit" grant

### ISSUE THREAD

**Issue by jessicamcinchak** [detroitledger/gnl_profile#92]
can we ditch the autofill for dates, organizations, and sources when "editing" a current grant, but keep it for "adding" new grants.

**Comment by bnchdrff** [comment]
Sounds like a good idea. I'll work on this!

**Comment by hampelm** [comment]
Ack this just bit me! I created three grants from three separate orgs. Then I edited their descriptions and found they had all been reassigned to the last organization I used.

**Comment by bnchdrff** [comment]
fixed & patched on live! thx for the tickler :wink:

**Comment by bnchdrff** [comment]
related to #61

**Comment by hampelm** [comment]
:+1: :+1:
