### ISSUE TITLE
Flags return a 404

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#93]
Creating a flag ([documentation](http://docs.detroitledger.apiary.io/#post-%2Fapi%2F1.0%2Fflags%2F%3Aid)) returns a 404.

To reproduce:

In Postman, send a POST to `https://data.detroitledger.org/api/1.0/flags/349` with the body

```
{
    "flag": {
        "target_id": 349,
        "note": "This is a duplicate of grant id 1822"
    }
}
```

When creating from backbone, I see [this behavior](https://github.com/jashkenas/backbone/issues/2542)

**Comment by bnchdrff** [comment]
api was expecting an un-wrapped flag object, so i changed things to work as the docs imply!

**Comment by hampelm** [comment]
I'm still getting a 404 (not a validation / poorly formed input error). Can you confirm the CURL or Postman test works on the live server?

**Comment by bnchdrff** [comment]
Don't include the id in the request.

**Comment by bnchdrff** [comment]
hmm, i tried updating the apiary docs to indicate this but my formatting must be off, or something. example curl:

```
curl --include \
     --request POST \
     --header "Content-Type: application/json" \
     --header "Accept: application/json" \
     --data-binary '{
    "flag": {
        "target_id": 1821,
        "note": "This is a duplicate of grant id 1822"
    }
}' \
     https://detroitledger.apiary-proxy.com/api/1.0/flags
```

**Comment by hampelm** [comment]
Works from postman to /flags! 
Just need to update docs then

**Comment by hampelm** [comment]
Looks like we'll need a CORS header, though:

```
XMLHttpRequest cannot load https://data.detroitledger.org/api/1.0/flags. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8888' is therefore not allowed access. 
```

**Comment by hampelm** [comment]
@bnchdrff Has this been deployed? I'm still getting an XHR error:

```
OPTIONS https://data.detroitledger.org/api/1.0/flags 405 (Not Allowed) jquery-1.10.0.js:4
XMLHttpRequest cannot load https://data.detroitledger.org/api/1.0/flags. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8888' is therefore not allowed access. 
```

**Comment by bnchdrff** [comment]
Try now... think i figured it out...

**Comment by hampelm** [comment]
Still no go. Can you test from the [flag branch](https://github.com/detroitledger/detroitledger/tree/flag) of the homepage? 

```
XMLHttpRequest cannot load https://data.detroitledger.org/api/1.0/flags. The 'Access-Control-Allow-Origin' header contains multiple values 'http://client.cors-api.appspot.com http://detroitledger.org http://www.detroitledger.org', but only one is allowed. Origin 'http://localhost:8888' is therefore not allowed access.
```

**Comment by bnchdrff** [comment]
fixed the cors thing by streamlining our code.. but now i'm running into backbone weirdness... the API expects an object `{flag:{target_id:'xxx' ,note:'xxx'}}` but backbone sends `{target_id:'xxx' ,note:'xxx'}`

i changed the API to take what backbone throws at us :grimacing:
