### ISSUE TITLE
Stats aren't updating?

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#96]
If you add / change a grant amount, the stats don't update. Are they super cached? 

https://data.detroitledger.org/api/1.0/stats.jsonp

**Comment by bnchdrff** [comment]
yes, they're cached indefinitely... what if i cleared the stats cache each time a grant is updated?

**Comment by hampelm** [comment]
Yeah! That'd work great. Would it be easy to cache the new stats when a grant is updated? Or are the queries fast enough that they wouldn't delay the front page rendering that much? 

If they're fairly slow, I'll rethink how we render the homepage, because it re-renders the whole page when we get the stats (which is bad anyways... I should fix that)

## 

Sent from mobile
(734) 846-5010
